# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  version: V1.0
  debug: 0
  cache: true
  internal: false

security:
  applicationKey: "45c1a4b6-59d3-4a6e-86bf-88a872f35845"
  secret: ""
  jwt:
    id:
    privateKey:
  dependencies:
      arc:
          auth: apikey
          location: agendaservice.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      brp:
          auth: apikey
          location: brpservice.local
          apiKey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      bc:
          auth: apikey
          location: betaalservice.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      bs:
          auth: apikey
          location: berichtservice.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      cc:
          auth: apikey
          location: contactcomponent.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      digispoof-interface:
          auth: apikey
          location: digispoof-interface.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      ds:
          auth: apikey
          location: digispoof-interface.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      eh:
          auth: apikey
          location: eherkenning-ui.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      grc:
          auth: apikey
          location: grafregistratiecomponent.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      ias:
          auth: apikey
          location: instemmingservice.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      irc:
          auth: apikey
          location: instemmingsregistratiecomponent.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      kvk:
          auth: apikey
          location: kvkservice.local
          apiKey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      lc:
          auth: apikey
          location: locatiecatalogus.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      ltc:
          auth: apikey
          location: landelijketabellencatalogus.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      mrc:
          auth: apikey
          location: medewerkerscatalogus.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      memo:
          auth: apikey
          location: memo-component.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      orc:
          auth: apikey
          location: orderregistratiecomponent.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      pdc:
          auth: apikey
          location: productenendienstencatalogus.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      ptc:
          auth: apikey
          location: procestypecatalogus.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      uc:
          auth: apikey
          location: user-component.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      vrc:
          auth: apikey
          location: verzoekregistratiecomponent.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      vtc:
          auth: apikey
          location: verzoektypecatalogus.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845
      wrc:
          auth: apikey
          location: webresourcecatalogus.local
          apikey: 45c1a4b6-59d3-4a6e-86bf-88a872f35845

php:
  repository: docker.io/conduction/protocomponent-php
  image: ghcr.io/conductionnl/begrafenisplanner-php
  tag: latest
  env: prod
  replicaCount: 2
  pullPolicy: Always
  trustedHosts: '^.+$'
  corsAllowOrigin: ['*']
  trustedProxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

redis:
  cluster:
    enabled: false
  redisPort: 6379
  usePassword: false
  enabled: false
  pullPolicy: IfNotPresent

nginx:
  repository: docker.io/conduction/protocomponent-nginx
  image: ghcr.io/conductionnl/begrafenisplanner-nginx
  tag: latest
  pullPolicy: Always
  replicaCount: 2

postgresql:
  enabled: true
  imageTag: 10-alpine
  # If bringing your own PostgreSQL, the full uri to use
  url: "psql://a:b@example.com/c"
  postgresqlUsername: "example"
  postgresqlPassword: "!ChangeMe!"
  postgresqlDatabase: "api"
  # Persistent Volume Storage configuration.
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  persistence:
    enabled: true
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  hostname: begrafenisplanner.local
  path: /
  annotations:
    # kubernetes.io/ingress.global-static-ip-name: chart-ip
    # kubernetes.io/ingress.class: gce
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace, you can also use cert-manager.
    # - hosts:
    # - example.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
